{
 "title": "K8s集群信息比较和查询",
 "tags": [
  "节点部署",
  "服务部署",
  "集群信息"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "monitor", "label": "集群", "query": "label_values(up,monitor)" },
   {
    "name": "Node",
    "query": "label_values(up{monitor=\"$monitor\"},kubernetes_io_hostname)"
   },
   {
    "name": "hostip",
    "label": "主机对应IP地址",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\",created_by_name!~\".*gray.*\",node=~\"$Node\"},host_ip)"
   },
   {
    "name": "service",
    "label": "服务",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\"},created_by_name)"
   }
  ]
 },
 "panels": [
  { "title": "机器组件部署表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点组件部署",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{monitor=\"$monitor\",node=~\"$Node\",namespace!~\"monitoring|kube-system\"})by(created_by_name)",
     "legendFormat": "{{ created_by_name}}"
    }
   ]
  },
  {
   "title": "服务所在节点",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{monitor=\"$monitor\",created_by_name=~\"$service\",namespace!~\"monitoring|kube-system\"})by(node,host_ip)",
     "legendFormat": "{{node}} ---- ip： {{host_ip}}"
    }
   ]
  },
  {
   "title": "CPU核数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "内存GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"$Node\"})/1024/1024/1024"
    }
   ]
  },
  { "title": "基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU利用率Top 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_io_hostname) (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"$Node\"}[2m])) / sum by(kubernetes_io_hostname) (machine_cpu_cores{kubernetes_io_hostname=~\"$Node\"}) * 100",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "MEM利用率Top 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by(kubernetes_io_hostname) (container_memory_rss{id=\"/\",kubernetes_io_hostname=~\"$Node\",monitor=\"$monitor\"}) / sum by (kubernetes_io_hostname)(machine_memory_bytes{kubernetes_io_hostname=~\"$Node\",monitor=\"$monitor\"}))*100 ",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "网卡流量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "入带宽",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))by(kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "出带宽",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by(kubernetes_io_hostname)(rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP连接数",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{monitor=~\"$monitor\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}