{
 "title": "服务单个POD基础监控",
 "description": "按照精确POD名称查看基础信息",
 "tags": [
  "POD",
  "K8S"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "monitor", "label": "集群", "query": "label_values(up,monitor)" },
   {
    "name": "Node",
    "query": "label_values(up{monitor=\"$monitor\"},kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\",namespace=~\"$namespace\"},pod)"
   },
   { "name": "status", "label": "status", "query": "label_values(status)" },
   { "name": "quantile", "label": "quantile", "query": "label_values(quantile)" },
   {
    "name": "host_ip",
    "label": "主机IP",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\",created_by_name!~\".*gray.*\",node=~\"$Node\"},host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "service级别监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m]))by(pod) ",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m]))by(pod_name) ",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{ pod}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}) by (pod_name)",
       "legendFormat": "{{ pod_name}}"
      }
     ]
    },
    {
     "title": "Pods network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m]))by(pod_name) ",
       "legendFormat": "-> {{ pod_name}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m]))by(pod_name)  ",
       "legendFormat": "<- {{ pod_name}}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m]))by(pod) ",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m]))by(pod)  ",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    },
    {
     "title": "HPA使用率%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_hpa_status_desired_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa) / count(kube_hpa_status_desired_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa)) / (sum (kube_hpa_spec_max_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa) / count (kube_hpa_spec_max_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa)) * 100",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod级别监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=~\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$Node\",pod_name=~\"$pod\"}[1m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=~\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"$Node\",pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{ pod}}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (pod)",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (pod)",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    },
    {
     "title": "pod restart times(5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate (kube_pod_container_status_restarts_total{monitor=\"$monitor\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (pod) * 300 >0",
       "legendFormat": "{{ $pod}}"
      }
     ]
    },
    {
     "title": "Containers CPU limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": " sum(kube_pod_container_resource_limits_cpu_cores{monitor=~\"$monitor\",namespace=~\"$namespace\",node=~\"$Node\",pod_name=~\"$pod\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(kube_pod_container_resource_limits_memory_bytes{monitor=~\"$monitor\",namespace=~\"$namespace\",node=~\"$Node\",pod_name=~\"$pod\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers级别监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (container_name, pod)",
       "legendFormat": "pod: {{ pod}} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      }
     ]
    },
    {
     "title": "Containers CPU usage / limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (container_name, pod_name) / (sum(kube_pod_container_resource_limits_cpu_cores{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod_name=~\"$pod\"}) by (container_name, pod_name)*1000*1000)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum(container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$service.*\"}) by (container_name, pod) / (sum(kube_pod_container_resource_limits_cpu_cores{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod=~\"$pod\"}) by (container_name, pod)*1000*1000)",
       "legendFormat": "pod: {{ pod}} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory usage / limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (container_name, pod_name) / sum(kube_pod_container_resource_limits_memory_bytes{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod_name=~\"$pod\"}) by (container_name, pod_name) * 100",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$service.*\"}) by (container_name, pod) / sum(kube_pod_container_resource_limits_memory_bytes{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod =~\"$pod\"}) by (container_name, pod) * 100",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      }
     ]
    },
    {
     "title": "Containers network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$pod\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (container_name, pod)",
       "legendFormat": "-> pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"$pod\"}[2m])) by (container_name, pod)",
       "legendFormat": "<- pod: {{ pod }} | {{ container_name }}"
      }
     ]
    }
   ]
  }
 ]
}