{
 "title": "服务service下所有POD基础监控",
 "tags": [
  "service",
  "POD",
  "K8S"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "monitor", "label": "集群", "query": "label_values(up,monitor)" },
   {
    "name": "Node",
    "label": "节点",
    "query": "label_values(up{monitor=\"$monitor\"},kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\"}, namespace)"
   },
   {
    "name": "service",
    "label": "服务名称",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\",namespace=~\"$namespace\"},created_by_name)"
   },
   {
    "name": "service2",
    "label": "服务名称",
    "query": "label_values(kube_service_info{monitor=\"$monitor\",namespace=~\"$namespace\"},service)"
   },
   { "name": "status", "label": "status", "query": "label_values(status)" },
   { "name": "quantile", "label": "quantile", "query": "label_values(quantile)" },
   {
    "name": "host_ip",
    "label": "主机IP",
    "query": "label_values(kube_pod_info{monitor=\"$monitor\",created_by_name!~\".*gray.*\",node=~\"$Node\"},host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "POD Top 10(可根据服务名称、节点进行排序)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service(服务负载均衡)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",monitor=\"$monitor\",pod_name=~\"$service.*\"}[2m])) ",
       "legendFormat": "{{$service}}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (service)",
       "legendFormat": "{{ $service }}"
      }
     ]
    },
    {
     "title": "Pods network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) ",
       "legendFormat": "-> {{ $service}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) ",
       "legendFormat": "<- {{ $service }}"
      }
     ]
    },
    {
     "title": "HPA使用率%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_hpa_status_desired_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa) / count(kube_hpa_status_desired_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa)) / (sum (kube_hpa_spec_max_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa) / count (kube_hpa_spec_max_replicas{hpa=~\"$service\",job=\"kubernetes-service-endpoints\",k8s_app=\"kube-state-metrics\",monitor=\"$monitor\",namespace=\"$namespace\"}) by (hpa)) * 100",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  { "title": "Pod(单个业务容器监控)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "pod restart times(5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kube_pod_container_status_restarts_total{monitor=\"$monitor\",namespace=~\"$namespace\",pod=~\"$service.*\"}[5m])) by (pod) * 300 >0",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Containers(POD内多容器监控)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{monitor=\"$monitor\",namespace=\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Containers CPU usage / limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod_name=~\"$service.*\"}) by (container, pod_name))",
       "legendFormat": "pod: {{ pod }} | {{ container }}"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{monitor=\"$monitor\",namespace=\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Containers memory usage / limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(kube_pod_container_resource_limits_memory_bytes{monitor=\"$monitor\",namespace=\"$namespace\",node=~\"^$Node$\",pod_name=~\"$service.*\"}) by (container, pod_name) ",
       "legendFormat": "pod: {{ pod }} | {{ container }}"
      }
     ]
    },
    {
     "title": "Containers network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{monitor=\"$monitor\",namespace=\"$namespace\",rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fs 读写 操作数(2m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_fs_reads_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}-读取"
      },
      {
       "expr": "sum (rate (container_fs_writes_total{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}[2m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}-写入"
      }
     ]
    },
    {
     "title": "Fs 当前IO (2m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (container_fs_io_current\t{monitor=\"$monitor\",namespace=\"$namespace\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",pod_name=~\"$service.*\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Pending",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Unknown",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Unknown\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) "
      }
     ]
    },
    {
     "title": "Waiting Reason",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_container_status_waiting_reason{namespace =~ \"$namespace\"})  by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Terminated Reason",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_container_status_terminated_reason{namespace =~ \"$namespace\"})  by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    }
   ]
  }
 ]
}