{
 "title": "节点数据",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "K8S" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "monitor", "label": "集群", "query": "label_values(up,monitor)" },
   {
    "name": "Node",
    "query": "label_values(up{monitor=\"$monitor\"},kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"Ready\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((count(kube_node_spec_unschedulable) - sum(kube_node_spec_unschedulable{})) / count(kube_node_spec_unschedulable)) * 100"
    }
   ]
  },
  {
   "title": "Taint",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_node_spec_taint{}) / sum(kube_node_status_condition{condition=\"Ready\"})) * 100"
    }
   ]
  },
  {
   "title": "Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_created)" }
   ]
  },
  {
   "title": "Schedulable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable) - sum(kube_node_spec_unschedulable{})"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{})"
    }
   ]
  },
  {
   "title": "Taint",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_node_spec_taint{})" }
   ]
  },
  {
   "title": "PIDPressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "MemoryPressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\",node=~\"^$Node$\"}) "
    }
   ]
  },
  {
   "title": "DiskPressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "NetworkUnavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\",status=\"true\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "OutOfDisk",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\",status=\"true\",node=~\"^$Node$\"}) "
    }
   ]
  },
  {
   "title": "CPU Request usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"}) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日CPU usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"} offset 24h ) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 24h ) * 100",
     "legendFormat": "昨日CPU usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"} offset 168h ) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周CPU usage"
    }
   ]
  },
  {
   "title": "Memory Request usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日Memory usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"} offset 24h) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 24h) * 100",
     "legendFormat": "昨日Memory usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"} offset 168h ) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周Memory usage"
    }
   ]
  },
  {
   "title": "CPU Limit usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"}) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日CPU usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"} offset 24h ) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 24h ) * 100",
     "legendFormat": "昨日CPU usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"} offset 168h ) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周CPU usage"
    }
   ]
  },
  {
   "title": "Memory Limit usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日Memory usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"} offset 24h) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 24h) * 100",
     "legendFormat": "昨日Memory usage"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"} offset 168h ) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周Memory usage"
    }
   ]
  },
  {
   "title": "CPU Request Top",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Request Top",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Base Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage (2m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 46 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 46 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 46 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日Memory usage"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 24h) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 24h) * 100",
     "legendFormat": "昨日Memory usage"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周Memory usage"
    }
   ]
  },
  {
   "title": "CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日CPU usage"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m] offset 24h )) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 24h ) * 100",
     "legendFormat": "昨日CPU usage"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m] offset 168h )) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周CPU usage"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "今日Filesystem usage"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 24h ) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 24h ) * 100",
     "legendFormat": "昨日Filesystem usage"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"} offset 168h ) * 100",
     "legendFormat": "上周Filesystem usage"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}